# Generated by Django 3.0.8 on 2020-09-21 18:43

from django.db import migrations, models
import django.db.models.deletion
import enoch.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to=enoch.shortcuts.product_image_upload_path)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField(default='00.00')),
                ('category', models.CharField(choices=[('SPC', 'SPC'), ('WPC', 'WPC'), ('Rockwood Board', 'Rockwood Board'), ('Toilet Partition', 'Toilet Partition')], default=('SPC', 'SPC'), max_length=200)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=55)),
                ('address', models.TextField()),
                ('total_price', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enoch.Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
