# Generated by Django 3.0.8 on 2020-09-13 18:39

from django.db import migrations, models
import enoch.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('enoch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=enoch.shortcuts.product_image_upload_path),
        ),
    ]
