# Generated by Django 3.0.8 on 2021-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enoch', '0003_auto_20210208_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPC Flooring', 'SPC Flooring'), ('WPC', 'WPC'), ('Rockwool Board', 'Rockwool Board'), ('HDF Board and accessories', 'HDF Board and accessories'), ('Others', 'Others')], default=('SPC Flooring', 'SPC Flooring'), max_length=200),
        ),
    ]
